### ISSUE TITLE
Automatic code style formatting

### ISSUE THREAD

**Issue by rootulp** [IndexCoop/index-ui#389]
**Describe the solution you'd like**
- Automatic code style formatting in this package. Likely with [Prettier](https://prettier.io/) + [ESLint](https://eslint.org/)

**Additional context**
- Consider enabling default React, TypeScript rules. Then consider adding https://eslint.org/docs/rules/sort-imports
- Motivation in https://github.com/SetProtocol/index-ui/pull/380#discussion_r713312466

**Comment by 0xModene** [comment]
I'm here for this, this would at minimum prevent any whitespace related merge/diff issues. We already have a prettier config. Perhaps we can vote on any new rules in #dev-public?

**Comment by tytarman** [comment]
@0xModene I've been working on an import linter. Just wanted to post here to claim the work I've already done on it. It's almost ready for a PR. Just cleaning up some final details, and it'll be ready next week (hopefully)

**Comment by 0xModene** [comment]
cool @tytarman I've assigned this to you then
