### ISSUE TITLE
Fix the background scrolling effect

### ISSUE THREAD

**Issue by tytarman** [IndexCoop/index-ui#620]
**Describe the bug**
On the app, after clicking/tapping on `Connect Wallet`, the overlay does not prevent the background from scrolling. This issue also occurs when the Mobile Menu is open on any mobile device.

**To Reproduce**

1. Go to `app.indexcoop.com`
2. Click on `Connect Wallet`
3. Scroll down to the bottom of the menu in the overlay, then continue scrolling and notice the background scrolling effect.

**Expected behavior**
The background scrolling effect should be disabled while an overlay is present. This provides a cleaner and more professional experience for users.

**Desktop (please complete the following information):**

- OS: All
- Browser: All
- Version: All

**Smartphone (please complete the following information):**

- Device: All
- OS: All
- Browser: All
- Version: All

**Comment by 0xModene** [comment]
If you've worked it already, go ahead. If not, I'd hold off
